import 'Styles/import.css';
import "Styles/fonts/icofont/icofont.min.css";
require('../index.html');
import './list_hide.js';
import './gallery.js';
import './mobile-menu_hide.js';
import './slider.js';
// import "https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.8.6/min/tiny-slider.js";
// import "https://fonts.googleapis.com/icon?family=Material+Icons";
// import "https://use.fontawesome.com/releases/v5.3.1/css/all.css";
// import "https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.8.6/tiny-slider.css";